"""Fix path

Revision ID: 751ed8dfa63a
Revises: d1375fceb99d
Create Date: 2022-11-14 09:10:23.027827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751ed8dfa63a'
down_revision = 'd1375fceb99d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
