"""Add port

Revision ID: 80db1bcf2064
Revises: 751ed8dfa63a
Create Date: 2022-11-14 09:12:47.509921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80db1bcf2064'
down_revision = '751ed8dfa63a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
