"""upd

Revision ID: 2557cc7b9e0e
Revises: 3888a085436b
Create Date: 2022-11-22 01:44:30.037587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2557cc7b9e0e'
down_revision = '3888a085436b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
