"""upd

Revision ID: 3888a085436b
Revises: 3fa770e6028f
Create Date: 2022-11-21 23:06:03.300658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3888a085436b'
down_revision = '3fa770e6028f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_book_book_id_fkey', 'author_book', type_='foreignkey')
    op.drop_constraint('author_book_author_id_fkey', 'author_book', type_='foreignkey')
    op.create_foreign_key(None, 'author_book', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'author_book', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_book', type_='foreignkey')
    op.drop_constraint(None, 'author_book', type_='foreignkey')
    op.create_foreign_key('author_book_author_id_fkey', 'author_book', 'author', ['author_id'], ['id'])
    op.create_foreign_key('author_book_book_id_fkey', 'author_book', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###
