"""Change many to many links

Revision ID: 3e2995d70269
Revises: e1b3195116ff
Create Date: 2022-11-21 20:01:00.357737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2995d70269'
down_revision = 'e1b3195116ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
