"""Remove some refs

Revision ID: 3fa770e6028f
Revises: c288780680bd
Create Date: 2022-11-21 23:05:31.856078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa770e6028f'
down_revision = 'c288780680bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
