"""Remove some refs

Revision ID: 6cf75018cdcb
Revises: b5e31b6cd63a
Create Date: 2022-11-21 22:03:24.980901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf75018cdcb'
down_revision = 'b5e31b6cd63a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'language', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'language_id')
    # ### end Alembic commands ###
