"""upd

Revision ID: 8a35fd8ee829
Revises: dc07aa1e2f0c
Create Date: 2022-11-22 01:48:42.719990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a35fd8ee829'
down_revision = 'dc07aa1e2f0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
