"""Remove some refs

Revision ID: c4b1123d5034
Revises: 6cf75018cdcb
Create Date: 2022-11-21 22:23:39.385788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b1123d5034'
down_revision = '6cf75018cdcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
