"""upd

Revision ID: 5ac6971749b3
Revises: 8a35fd8ee829
Create Date: 2022-11-22 01:49:36.380502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac6971749b3'
down_revision = '8a35fd8ee829'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
