"""upd

Revision ID: 7207f9c9f7ee
Revises: c2b63c275073
Create Date: 2022-11-22 02:31:01.388573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7207f9c9f7ee'
down_revision = 'c2b63c275073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
