"""upd

Revision ID: a0b785e7e3cc
Revises: 2557cc7b9e0e
Create Date: 2022-11-22 01:47:11.514322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b785e7e3cc'
down_revision = '2557cc7b9e0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
