"""upd

Revision ID: a6db039e15ea
Revises: 7207f9c9f7ee
Create Date: 2022-11-22 02:32:32.256586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6db039e15ea'
down_revision = '7207f9c9f7ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
