"""Remove some refs

Revision ID: c288780680bd
Revises: c4b1123d5034
Create Date: 2022-11-21 22:36:58.707041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c288780680bd'
down_revision = 'c4b1123d5034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_language_author_id_fkey', 'author_language', type_='foreignkey')
    op.drop_constraint('author_language_language_id_fkey', 'author_language', type_='foreignkey')
    op.create_foreign_key(None, 'author_language', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'author_language', 'language', ['language_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_language', type_='foreignkey')
    op.drop_constraint(None, 'author_language', type_='foreignkey')
    op.create_foreign_key('author_language_language_id_fkey', 'author_language', 'language', ['language_id'], ['id'])
    op.create_foreign_key('author_language_author_id_fkey', 'author_language', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###
